###
GET http://localhost:3000/api/attendance

###
GET http://localhost:3000/api/attendance/with-user

###
POST http://localhost:3000/api/attendance
Content-Type: application/json

{
  "UserID": 1,
  "Date": "2026-01-17",
  "Status": "มาทำงาน",
  "CheckInTime": "08:30",
  "CheckOutTime": "17:00"
}

###
PUT http://localhost:3000/api/attendance/1
Content-Type: application/json

{
  "Date": "2026-01-17",
  "Status": "มาทำงาน",
  "CheckInTime": "08:00",
  "CheckOutTime": "19:00"
}

###
DELETE http://localhost:3000/api/attendance/1

###